name: "Publish Rails Auto-Instrumentation"

on:
  push:
    paths:
      - 'autoinstrumentation/rails/**'
      - '.github/workflows/publish-autoinstrumentation-rails.yaml'
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Read version
        run: echo VERSION=$(cat autoinstrumentation/rails/Gemfile | grep opentelemetry-sdk | cut -d ',' -f2 | jq -r) >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-rails
          tags: |
            type=match,pattern=v(.*),group=1,value=v${{ env.VERSION }}

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: autoinstrumentation/rails
          push: true
          build-args: version=${{ env.VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
